### ISSUE TITLE
Make notifiers section optional when ALL domains are accessible via single factor

### ISSUE THREAD

**Issue by khimaros** [clems4ever/authelia#100]
This would help ease initial testing now that the filesystem notifier has been removed. Alternatively, add the filesystem notifier back.

**Comment by clems4ever** [comment]
Hello @sllawap, thank you for the proposal.
Actually, removing filesystem notifier don't change anything since it has been replaced by a fake smtp server that can be queried via a REST API.
I think this proposal is related to #73. Have you seen it already?

By saying "disable notifications", do you mean disable 2nd factor? Indeed, if there is no notification anymore, you won't be able to get the secret and use second factor.

**Comment by sllawap** [comment]
Thank you for your reply!

It's possible that I'm misunderstanding the purpose of notifiers. From reading the config template, it seemed these were only used for registration. If the service owner uses a different registration mechanism, is the notifier still needed?

Is the fake SMTP server built into Authelia or does it require running a separate service? How does one enable/use it in the config?

**Comment by clems4ever** [comment]
Hello @sllawap, there are two kind of second factor supported in Authelia (TOTP and U2F) and both need the user to register because they both need to define a secret. Notifiers (basically emails as of now) are used to do identity validation. Basically, when you need to register the secret for either of the second factor method, Authelia verifies you are who you claim to be by sending an email  with a link to your email address defined in the LDAP. You must confirm reception before being able to define the secret. So to sum it up, notifier is just a strategy to do identity validation and SMTP and GMail are the only supported options right now.

The fake SMTP is not built into Authelia, this is an external component called 'mailcatcher' I package with the test environment but which is not shipped with Authelia. It's just for testing purpose.
https://mailcatcher.me/

**Comment by sllawap** [comment]
What you've described makes sense for services which use open registration. How do you anticipate this being used for services where the registration is centrally provisioned?

**Comment by clems4ever** [comment]
Hello @khimaros , actually this is not a user registration. Username and password should already be in the LDAP. This procedure is just a layer of security. Imagine, someone finds your password, the hacker can login and then, without identity validation, he would be able to change your secret and pass the second factor.

Concerning your question, I'm not sure I got the point. Can you please clarify if the above does not answer the question?

**Comment by clems4ever** [comment]
@khimaros , did my answer help?

**Comment by khimaros** [comment]
Would it be sensible to allow notifications to be disabled for cases where 2FA is being used?

**Comment by clems4ever** [comment]
@khimaros , let me clarify some things:
- When setting up Authelia, the users should already be in the LDAP with (username, password and email address). Authelia does not handle user registration.
- Notifiers (SMTP and GMail) are used only when a user needs to register a secret for TOTP or to register a U2F device. Those registrations create secrets and save them in the DB (mongo) and not in LDAP.

I still don't see what disabling notifiers is supposed to solve in your setup.

**Comment by khimaros** [comment]
@clems4ever -- removing the hard SMTP dependency makes it easier to do initial deployment of SSO using LDAP without U2F. There really aren't other tools that fill this niche so well and so nicely as Authelia.

The SMTP dependency is friction for initial setup, especially since the SMTP notifier does not work with (for example) networks which are configured for auth-less delivery from any machine on a given netblock.

**Comment by clems4ever** [comment]
@khimaros , I see. Authelia does not start if you don't provide SMTP or GMail and all your domains are configured with single_factor.

One quick workaround could be to set the **filesystem** notifier to /dev/null. In the meantime I will make the notifier section optional. Sounds good?

**Comment by khimaros** [comment]
Actually, this might be enough! When I filed this bug originally the filesystem notifier had been removed but I see now that change has been reverted. I will verify that it works shortly.

**Comment by clems4ever** [comment]
#172 should solve your issue officially. Now, if Authelia protects ALL sub-domains with single factor (meaning **default_method** is **single_factor** and ALL **per_subdomains_method** are **single_factor**) should allow you to not define any notifier. Moreover, the change prevents any access to second factor endpoints (for security reason).
