### ISSUE TITLE
can two factor authentication be added on top of NGINX basic HTTP authentication

### ISSUE THREAD

**Issue by manas86** [clems4ever/authelia#104]
Hi

I have implemented basic HTTP authentication in NGINX using https://www.digitalocean.com/community/tutorials/how-to-set-up-basic-http-authentication-with-nginx-on-centos-7. But I was wondering if I could use 2 factor authentication on top of above basic one. If so, can anyone guide me the right direction to address it .

**Comment by clems4ever** [comment]
Hello @manas86, if you wish to use Authelia, you won't need the setup you've gone through since Authelia will handle the authentication with login/password as a first factor. Basically, Authelia is the authority for users authentication; it handles both first and second factor. So, there is not much configuration to be done at the level of nginx since nginx will only use the **auth_request** module (http://nginx.org/en/docs/http/ngx_http_auth_request_module.html) to forward session verification requests to Authelia and redirects if the user is not authenticated.
I advise you to deploy Authelia in fews seconds by following the README and try it out yourself :).

Thanks,
Clément.

**Comment by clems4ever** [comment]
Hello @manas86, did it answer your question? Can I close the ticket?
