### ISSUE TITLE
No redirect, verfication ok

### ISSUE THREAD

**Issue by jkaberg** [clems4ever/authelia#14]
Somehow, this doesn't work:
```
Parse configuration file: /etc/auth-server/config.yml
{ port: '80',
  ldap_url: 'ldap://ipa.xxxxx.local',
  ldap_users_dn: 'cn=users,cn=accounts,dc=xxxxx,dc=local',
  ldap_user: 'uid=xxxxx,cn=sysaccounts,cn=etc,dc=xxxxx,dc=local',
  ldap_password: 'xxxxx',
  session_secret: 'xxxxx',
  session_max_age: xxxxx,
  store_directory: '/var/lib/auth-server/store',
  logs_level: 'debug',
  notifier: { filesystem: { filename: '/var/lib/auth-server/notifications/notification.txt' } } }
Listening on 80...
info: 1st factor: Starting authentication of user "joel"
debug: 1st factor: Start bind operation against LDAP
debug: 1st factor: username=joel
debug: 1st factor: base_dn=cn=users,cn=accounts,dc=xxxxx,dc=local
info: 1st factor: LDAP binding successful
debug: 1st factor: Retrieve email from LDAP
debug: 1st factor: document={"dn":"uid=joel,cn=users,cn=accounts,dc=xxxxx,dc=local","controls":[],"mail":"joel@xxxxx.local"}
debug: 1st factor: Retrieved email is joel@xxxxx.local
info: POST 2ndfactor totp: Initiate TOTP validation for user joel
debug: POST 2ndfactor totp: Fetching secret for user joel
debug: POST 2ndfactor totp: TOTP secret is {"userid":"xxxxx","secret":{"ascii":"s!yoi0)}kooTrJ>!4qsmmFs4kF,/LK,I","hex":"xxxxx","base32":"xxxxx","otpauth_url":"otpauth://totp/SecretKey?secret=xxxxx"},"_id":"xxxxx"}
debug: POST 2ndfactor totp: TOTP validation succeeded
```

Virtual host sbox:
```
server {
	listen 192.168.1.11:443 ssl http2;

	server_name sbox.xxxx.local;

	access_log /var/log/nginx/xxxx.local/sbox.xxxx.local-access.log;
	error_log /var/log/nginx/xxxx.local/sbox.xxxx.local-error.log;

	auth_request /authentication/verify;

	auth_request_set $user $upstream_http_x_remote_user;
	proxy_set_header X-Forwarded-User $user;
	auth_request_set $groups $upstream_http_remote_groups;
	proxy_set_header Remote-Groups $groups;
	auth_request_set $expiry $upstream_http_remote_expiry;
	proxy_set_header Remote-Expiry $expiry;

	error_page 401 = @error401;
	location @error401 {
		return 302 https://auth.xxxx.local/authentication/login?redirect=$scheme://$http_host$request_uri;
	}

	location /authentication/ {
		proxy_set_header  X-Original-URI $scheme://$http_host$request_uri;
		proxy_set_header  Host $http_host;
		proxy_set_header  X-Real-IP $remote_addr;

		proxy_pass http://192.168.1.16/authentication/;
	}

	location /authentication/js/ {
		proxy_pass http://192.168.1.16/js/;
	}

	location /authentication/img/ {
		proxy_pass http://192.168.1.16/img/;
	}

	location /authentication/css/ {
		proxy_pass http://192.168.1.16/css/;
	}

	location / {
		include /etc/nginx/proxy_params;
		proxy_http_version 1.1;
		proxy_pass http://10.0.10.5:8112/;
	}
}
```

Virtual host auth:
```
server {
	listen 192.168.1.11:443 ssl http2;

	server_name auth.xxxx.local;

	access_log /var/log/nginx/xxxx.local/auth.xxxx.local-access.log;
	error_log /var/log/nginx/xxxx.local/auth.xxxx.local-error.log;

	location / {
		rewrite ^/$ authentication/login redirect; break;
	}

	location /authentication/ {
		proxy_set_header  X-Original-URI $request_uri;
		proxy_set_header  Host $http_host;
		proxy_set_header  X-Real-IP $remote_addr;
		proxy_pass http://192.168.1.16/authentication/;
	}

	location /authentication/js/ {
		proxy_pass http://192.168.1.16/js/;
	}

	location /authentication/img/ {
		proxy_pass http://192.168.1.16/img/;
	}

	location /authentication/css/ {
		proxy_pass http://192.168.1.16/css/;
	}
}
```

I'm out of ideas as to why this doesn't work. I get redirected properly to the auth page, where I auth and get to enter my 2FA. But then I get redirected back to the login page (and not the proper url). I can see the cookie beeing generated and stored within Chrome so that seems OK

**Comment by clems4ever** [comment]
Are you using  auth.xxxx.local for authentication and sbox.xxxx.local for accessing the secret? 

If yes, the issue might come from the cookie. Indeed, the cookie might be restricted to the domain it has been produced for.

Can you confirm the domain associated to the cookie?

**Comment by jkaberg** [comment]
Yes the domain associated with the cookie is the auth.xxxx.local domain (and not sbox.xxxx.local). Would it be possible to add some kind of wildcard functionality? eg *.xxxx.local is authenticated? (just thinking out loud)

**Comment by clems4ever** [comment]
Well, I think it could be possible as per
http://stackoverflow.com/questions/18492576/share-cookie-between-subdomain-and-domain
.

Do you confirm your cookie is restricted to auth.xxxx.local by inspecting
the request with your browser?

*Clément Michaud*
*FO Software engineer at Murex.*
(+33) 7 69 03 67 09

**Comment by jkaberg** [comment]
Not entirely sure what you're looking for, but this is the cookie I got for auth.xxxx.local

![image](https://cloud.githubusercontent.com/assets/613363/23950828/96695266-098c-11e7-830b-18b7273ef31b.png)

**Comment by clems4ever** [comment]
It clearly seems to be your problem. The domain of your cookie is
auth.xxxx.local. Thus, it can only be acknowledged by that specific domain.
I think a change in the code is required so that it produces a cookie for
the broader domain xxxx.local as it is explained in the stackoverflow
thread I linked earlier.

A workaround would be to use only one domain. If it is not possible on your
side, I need to check how hard it would be to create a cookie with a
broader scope.

**Comment by jkaberg** [comment]
@clems4ever A domain wide cookie (perhaps optional in the config where it would default to subdomain?) would be for the best. I got a lot of services running on various sub domains and getting them all to co-exist on a single sub domain would be asking for much (..trouble)

**Comment by jkaberg** [comment]
@clems4ever I'm by no means an javascript guy, but [this ](https://github.com/expressjs/session/blob/2604a6cbac9a77b4e06959e8aebe65b50ccb9491/README.md#cookiedomain) might interest you

**Comment by jkaberg** [comment]
Succsess, it works! Adding ```domain: 'xxxx.local'``` as a test to src/lib/server.js after line [37](https://github.com/clems4ever/authelia/blob/master/src/lib/server.js#L37) fixes this. Not the most elegant solution as this hardcode's it, but atleast it shows it's possible. Now you just need an function to strip out the base domain and top domain 😄

**Comment by clems4ever** [comment]
This is awesome! I will implement it right away in a more sustainable way.

No problem you are not a javascript guy. Me neither but the language is
bloody fast for prototyping. I'm more a C++ guy, btw.

Just out of curiosity, what are you implementing authelia for? Personal
projects? Company web services?

Le 15 mars 2017 18:41, "Joel Kåberg" <notifications@github.com> a écrit :

Succsess, it works! Adding domain: 'xxxx.local' as a test to
src/lib/server.js after line 37
<https://github.com/clems4ever/authelia/blob/master/src/lib/server.js#L37>
fixes this. Not the most elegant solution as this hardcode's it, but
atleast it shows it's possible. Now you just need an function to strip out
the base domain and top domain 😄

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/clems4ever/authelia/issues/14#issuecomment-286822164>,
or mute the thread

**Comment by clems4ever** [comment]
Great! AFAIK, I use it with U2F for protected services in a cluster.

This is a pleasure talking to you. I'm currently working on a fix. I will add a **domain** parameter in the config so that you can specify whatever you want. I decided to do it this way because the domain is required during the initialization of the server.

**Comment by clems4ever** [comment]
Hello @jkaberg , #17 gives you a way to specify your domain in the config file so that the cookies are shared by all subdomains of your domain.

**Comment by jkaberg** [comment]
Thanks a lot @clems4ever for the updates. Would you mind pushing an update to docker hub? Ideally you could set up an automatic build on docker hub and it will build new images as you push new commits to master branch on Github 😄

**Comment by clems4ever** [comment]
Indeed, I did not setup automatic push on docker hub with travis yet. I
will do it today and keep you posted once done.

Le 16 mars 2017 09:16, "Joel Kåberg" <notifications@github.com> a écrit :

Thanks a lot @clems4ever <https://github.com/clems4ever> for the updates.
Would you mind pushing an update to docker hub? Ideally you could set up an
automatic build on docker hub and it will build new images as you push new
commits to master branch on Github 😄

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/clems4ever/authelia/issues/14#issuecomment-286986640>,
or mute the thread

**Comment by clems4ever** [comment]
Hello @jkaberg, automatic push to Dockerhub is enabled and the latest image is available.

**Comment by jkaberg** [comment]
Thanks @clems4ever !
