### ISSUE TITLE
Is it possible to do HA / clustering ?

### ISSUE THREAD

**Issue by BankaiNoJutsu** [clems4ever/authelia#236]
Hello! And thank you for this beautiful software ! I was wondering if there was any HA Support? Like pacemaker/corosync with a VIP for example.

I seem to remember that there is something written about the storage being high availability? But how does it work?
Edit: High-availability using a highly-available distributed database and KV store.

If not i will look into it.

**Comment by clems4ever** [comment]
Hello @BankaiNoJutsu , indeed Authelia can be HA provided that your Redis and Mongo are configured correctly. This means that if they are in HA mode, you can have as many instances of Authelia as you want in the cluster and there is no need for cookie stickiness since the user sessions are stored in the Redis.

However, please note that Authelia only supports one address for the LDAP server so you need to load-balance it yourself if you want the LDAP not being a single point of failure.

Is it clear? Please re-open the ticket if it's not or if you have other questions. Also, do not hesitate to give me feedback on what could be improved in the doc if it was unclear at the beginning or you can even improve it yourself if you wish!

Thanks.
