### ISSUE TITLE
Build for ARM

### ISSUE THREAD

**Issue by itdaboyz** [clems4ever/authelia#318]
Hi,

It would be great to have builds for ARM plateforms.

Thank you

**Comment by clems4ever** [comment]
Hello @itdaboyz , since this is all typescript my guess is you only have to install an ARM version of node and that's it. Am I wrong?

**Comment by clems4ever** [comment]
You can also choose to go with Docker if this is an option.

**Comment by itdaboyz** [comment]
Maybe ? I tried to deploy Authelia using Docker Compose, following exemples, and I got `standard_init_linux.go:207: exec user process caused "exec format error"` so I assumed it was a wrong plateform issue.
I don't know how I could install a different node version as it should be called when the authelia image is loaded.

**Comment by clems4ever** [comment]
Ok, I think the problem is due to the fact that indeed the node version is x86_64 and some built libraries (mainly for cryptography) are built for x86 as well. If you can provide a VM to reproduce the error, we could figure this out and introduce it in the CI.
Perhaps you can check: https://ownyourbits.com/2018/06/27/running-and-building-arm-docker-containers-in-x86/

**Comment by itdaboyz** [comment]
I don't think to emulate x86_64 is the best way to get Authelia working on ARM. This would be slow and dependent from other libs. I'm not sure how much it represent but it would only require a different build with ARM version of integrated nodes.
I would gladly provide you a VM but I don't really know how to do it.

I'm not a dev so I can't really help, my use case is to put a media server on my Raspberry Pi with Docker-Compose for the ease of maintenance and Traefik for deployment. Authelia seems to be a good way to add security on this.

It's surprising no one asked before for ARM builds has it becomes more used now with Docker support for it.

**Comment by clems4ever** [comment]
Hello @itdaboyz , for the use case of a media center I guess you can simply enable authentication in the app and that's it; you'd probably not have 2FA though but is it so important for a media center?

The real issue arises when you put more services on the device with various level of importance. This second use case can probably be handled with OAuth, your services running on your ARM device and with Authelia running on an x86 device (but OAuth is not yet implemented, the apps must support it and you need two devices). So, for you this means that either you have this additional device to run Authelia or I create an Authelia as a service that you can subscribe to for a few bucks per month. What do you think?

Otherwise, we can try to make Authelia work on ARM but I have so many features to implement already that I won't push for this one unless there are more people interested.

**Comment by itdaboyz** [comment]
The issue is that every app has its own authentication (and not always a good one), so it's not possible to easily manage users. 2FA wasn't my priority.

This idea is interesting but not for my use case. I want to self-host everything, or the maximum possible. Regarding the Authelia as a service, I think that could be something great if you want to have customers and start a business. I don't think this will suits my needs (regarding the self-hosting part), but I see a opportunity on that market. I'll keep the idea of the second device though.

I understand and even if we are a lot asking, nothing force you to do it. I believe you do this on your free time and we are not your customers.

**Comment by clems4ever** [comment]
Hello @itdaboyz , I can investigate but as I said this is unfortunately not my priority as I have already plenty of must have features. You are right, this is a side project. I'm hardly trying to make it more accessible so that other users can help me improve it and solve particular problems such as yours. It already started with the support of Traefik done by a couple of users following the project, this is really nice.

I'll keep the issue open and I'll have a look if I have time but I can't promise anything. On your side if you want to move forward, you can prepare a ARM image for QEMU and try to run the build script. You can have a look at: https://www.aurel32.net/info/debian_arm_qemu.php.

**Comment by lbischof** [comment]
I  built the few other arm Docker images with Drone.io, but I can't seem to figure out how I can build Authelia inside another Docker container, because the build scripts depend on Docker itself.

**Comment by nightah** [comment]
I've actually attempted to build authelia with QEMU and it seemed to get stuck indefinitely, I need to dig in further to understand what the issue here is and if we can resolve it for upstream builds.

If not I've got a RPi laying around I might be able to do some testing with to rule out some potential problems, stay tuned.

**Comment by ahmedmagdiosman** [comment]
Hi. I've tried to compile this repo on a RPi without much success. I'm not a web developer so I'm not sure if I'm building this correctly. It seems that the Dockerfile is first looking for a compiled node app in `dist/server` which I guess is compiled using `authelia-scripts-build`. So my first step is to get this script working properly.

First, I ran `bootstrap.sh`. The npm package "chromedriver" stopped support for linux 32bit. I've worked around it by downgrading to the last compatible version (v2.24) which would've been fine except npm warns there is a security vulnerability with this version. Anyway, I ran `authelia-scripts-build` which complained that `react-scripts` is missing (easy fix with `npm i react-scripts`). But after that I get an error that I'm not sure how to fix `Cannot find name 'unknown'.` which looks like a typescript error.

I'm afraid even if it's fixable, having an old chromedriver version is not great security-wise. Like I said, I know little about web development but I hope this package is not absolutely required, then maybe there's a chance for an ARM build. 

It would be awesome if @clems4ever  could explain how to properly build this `dist` directory and any non-obvious dependencies that are needed (I was missing bash, python, g++,make when I tried building it inside a node:alpine docker container, but I guess that's normal since it was not meant to be compiled in a minimal linux environment) and I'll try to give it another shot.

**Comment by Rick-Jongbloed** [comment]
I am actually trying to build Authelia on armhf via drone.io I'm out this weekend, but I got stuck on not finding a dist directory to copy the compiled binaries from. Also due to Kaniko I had to switch to a debian based distro. 

You can checkout my tries on https://github.com/Rick-Jongbloed/authelia-arm and https://github.com/Rick-Jongbloed/authelia

Also the dev dependencies depend on chrome driver, which is not available for armhf.

I'll keep working on it until it works, but any tips would be appreciated:-)

**Comment by Rick-Jongbloed** [comment]
For anyone wondering, this drone script + dockerfile got me a working Authelia on arm!

**.drone.yml:**
```

kind: pipeline
name: authelia-arm

platform:
  os: linux
  architecture: arm
  variant: 7

steps:
- name: clone-authelia
  image: drone/git
  commands: 
  - git clone https://github.com/clems4ever/authelia

- name: build-client-server
  image: arm32v7/node:8.15-slim
  # environment:
  #   npm_config_loglevel: silent #- npm_config_loglevel=info npm install --production    # loglevel can be silent, warn, info, verbose, silly 
  commands:
  - cd authelia
  - apt update
  - apt install -y --no-install-recommends make g++ python
  - cd client
  - npm install
  - CI=false npm run build # should really fix the warnings so CI=false isnt needed
  - cd ..
  - sed -i '/chromedriver/d' package.json # Remove chromedriver as it's only used for tests
  - npm install
  - node_modules/.bin/tslint -c server/tslint.json -p server/tsconfig.json
  - node_modules/.bin/tsc -p server/tsconfig.json
  - mkdir -p dist/server/src/resources
  - cp server/src/resources/** dist/server/src/resources/
  - node_modules/.bin/typescript-json-schema -o server/src/lib/configuration/Configuration.schema.json --strictNullChecks --required server/tsconfig.json Configuration
  - cp server/src/lib/configuration/Configuration.schema.json dist/server/src/lib/configuration
  - mv client/build dist/server/src/public_html

- name: publish-authelia
  image: your-registry/drone-plugins/kaniko:latest
  settings:
    registry: your-registry
    repo: clems4ever/authelia
    tags: latest
    log: info
```


**Dockerfile**

```
FROM arm32v7/node:8.15-slim

WORKDIR /usr/src

COPY authelia/package.json /usr/src/package.json

RUN apt update \
    && apt install -y \
        python \
        make \
        g++ \
    && npm install --production \
    && rm -rf /var/lib/apt/lists/*

COPY authelia/dist/server /usr/src/server

EXPOSE 9091

VOLUME /etc/authelia
VOLUME /var/lib/authelia

CMD ["node", "server/src/index.js", "/etc/authelia/config.yml"]

```

**Comment by Stolz** [comment]
I managed to successfully build the image for both x86_64 and arm with a single [multi-stage](https://docs.docker.com/develop/develop-images/multistage-build/) `Dockerfile`. Thanks to @Rick-Jongbloed for doing all the heavy lifting. It uses the official Node image based in Alpine. It took just a couple of minutes to build in my x86_64 machine but more than 1 hour to build in my ARM machine (OrangePi+2E).

### Dockerfile

    FROM node:8-alpine AS builder

    RUN apk --update add make g++ python git && \
    git clone --depth=1 https://github.com/clems4ever/authelia && \
    cd authelia/client && \
    npm install && \
    npm run build && \
    cd .. && \
    sed -i '/chromedriver/d' package.json && \
    npm install && \
    node_modules/.bin/tslint -c server/tslint.json -p server/tsconfig.json && \
    node_modules/.bin/tsc -p server/tsconfig.json && \
    mkdir -p dist/server/src/resources dist/server/src/lib/configuration && \
    cp server/src/resources/* dist/server/src/resources/ && \
    node_modules/.bin/typescript-json-schema -o server/src/lib/configuration/Configuration.schema.json --strictNullChecks --required server/tsconfig.json Configuration && \
    cp server/src/lib/configuration/Configuration.schema.json dist/server/src/lib/configuration && \
    mv client/build dist/server/src/public_html


    FROM node:8-alpine

    WORKDIR /usr/src

    COPY --from=builder authelia/package.json .

    RUN apk --update add --no-cache --virtual .build-deps make g++ python && npm install --production && apk del .build-deps

    COPY --from=builder authelia/dist/server /usr/src/server

    EXPOSE 9091

    VOLUME /etc/authelia
    VOLUME /var/lib/authelia

    CMD ["node", "server/src/index.js", "/etc/authelia/config.yml"]


### docker-compose.yml

    version: '3'
    
    services:
    
      authelia:
        build: .
        container_name: authelia
        hostname: authelia
        image: stolz/authelia
        ports:
          - "9091:9091"
        restart: unless-stopped
        volumes:
          - ./config.yml:/etc/authelia/config.yml

**Comment by clems4ever** [comment]
Multi arch will be available in v4: https://github.com/clems4ever/authelia/pull/430 once the first release is done likely in a couple of days.  The time for me to provide a migration tool to go from v3 to v4 easily. In the meantime the docker images should be available with the master tag for beta testers.

**Comment by clems4ever** [comment]
Thanks @nightah for this very nice contribution.
