### ISSUE TITLE
Support for more than one top-level domain

### ISSUE THREAD

**Issue by instantlinux** [clems4ever/authelia#321]
I have two top-level domains; authelia is working well for multiple subdomains of one domain. But I get a redirect loop when I try to add a FQDN in a different top-level name. The documented examples are silent on this topic. Is there currently a way to make this work: is my request here for clarified doc, or is this a new feature I'm requesting?

I don't mind having to sign in separately for each TLD, but it would be a pain to maintain separate TOTP tokens for each.

**Comment by clems4ever** [comment]
Hello @instantlinux , Authelia cannot run with two top-level domains. This is simply due to how cookies work. One cookie is normally bound to one subdomain but in the case of Authelia the cookie is bound to all subdomains of the top-level domain.
So, when authenticating the portal will produce a cookie for the given it is served from.

I guess the only solution is to have 2 instances for your two domains but unfortunately you'll need to authenticate for each one of them. Sorry.
