### ISSUE TITLE
default theme has a large empty space above login box

### ISSUE THREAD

**Issue by khimaros** [clems4ever/authelia#326]
The whitespace is so large that it causes the login box to run below the fold.

I've been able to reproduce this in ChromeOS, Chrome on Android, and Firefox Focus on Android.

Opening up Developer Tools and deleting the <canvas> element causes everything to look sensible again. It's not clear to me what the purpose of that element is.

![image](https://user-images.githubusercontent.com/231498/53282234-b8f73780-36e9-11e9-92f2-986c93ea1420.png)

**Comment by khimaros** [comment]
And indeed this new 400x300 canvas element was introduced with the creation of the new themes functionality and was not present before: https://github.com/clems4ever/authelia/blob/6c4d06b2a8b42a062f4b4ddfcb57d23e6ef99295/server/src/views/layout/layout.pug

@BankaiNoJutsu for visibility.

**Comment by BankaiNoJutsu** [comment]
Hello @khimaros,

Indeed this is an element which is not needed for the default theme. You can test my fork on my repo, where this was fixed.

**Comment by clems4ever** [comment]
@khimaros, a new UI is coming up very soon. It will be looking a bit more professional and will allow to implement an admin portal more easily. Stay tuned, it's coming in the next few days.

**Comment by clems4ever** [comment]
@khimaros , the new UI reached the master. As I explained to @BankaiNoJutsu , I needed to do this re-write because I'd like to enable more complex management scenarii, like managing keys and devices, implement advanced audit logs so that one can point a non legitimate authentication.

@BankaiNoJutsu, you can resume your work on theming knowing the new UI is in React and using Sass now. This will be easier to implement new themes and avoid code duplication as in your previous contribution. I'll try to add back the dark theme if I have a bit of time.

**Comment by clems4ever** [comment]
This is now fixed in latest version of Authelia. I have not added back the dark theme yet though.
