### ISSUE TITLE
Feature request: allow TOTP to be the first factor

### ISSUE THREAD

**Issue by SurinameClubcard** [clems4ever/authelia#341]
I'd like the change the order of authentication (after registration), in such a way that for some services, only username+TOTP (or username+U2F) is requested by Authelia, not the password. A use case for this is a simple service that already requires u+p by itself. I'd like to protect that service with an extra factor.

**Comment by clems4ever** [comment]
Hello @SurinameClubcard , I'm afraid that what you request defeats the purpose of 2FA and therefore will not fit into Authelia. Moreover, it will be technically complicated to implement because it would require to disable a lot of features, make the first and second factors configurable, the ACLs would probably need to change, etc...

Can't you simply drop the auth from the backend to replace it by Authelia's workflow?
Do your backend support OAuth? If yes, it will probably be a better option when the support is added to Authelia.

In the meantime, if you trust your network, you can use nginx to forward a header telling the backend that a given user is authenticated. Check out X-Forwarded-User in the nginx configuration of the project. I implemented it to support my Jenkins (https://plugins.jenkins.io/reverse-proxy-auth-plugin) as a backend even if I don't really like this way of doing since it's not really secure. It's kind of a workaround that should be replaced by OAuth at some point.

**Comment by SurinameClubcard** [comment]
Ok, I understand. I was hoping this would be an easy change, but it isn't unfortunately.
