### ISSUE TITLE
Email variable

### ISSUE THREAD

**Issue by NegativeFeedback** [clems4ever/authelia#358]
After much trial and error I have a semi working nginx and authelia server. My two issues is that when I receive the email to enroll a client  the link shows as https://undefined/#/ but I have every domain filled in on config. If I fix the domain and manually add the url with the correct token I get 
![image](https://user-images.githubusercontent.com/1072659/56344376-dcd37880-6182-11e9-8944-e7640a542664.png)
not sure if those two things are related I dont see anything in the log except if I retry it says no u2f registration document found.

I also see that" Starting registration for appId 'https://undefined''"

Finally I think I might just not understand the doc/nginx.m example because once I auth it fails, do I just add a document root to that server block or how do I I add the actual content once past the 2fa screen?

**Comment by clems4ever** [comment]
Hello @NegativeFeedback ,
have you upgraded from an older version or is it your first setup?
This behavior appears because X-Forwarded-Host is not provided by the proxy in the requests to Authelia. Normally this header is set in the doc you mention. Otherwise, you can also have a look at https://github.com/clems4ever/authelia/blob/master/example/compose/nginx/portal/nginx.conf.ejs.

Do you deploy by hand or do you use Kubernetes?

Regarding your second question, `auth_request /auth_verify;` is the key. This statement makes nginx forward the auth requests to the virtual endpoint /auth_verify that is declared to forward the request to the /api/verify endpoint of Authelia. When the response comes back to nginx, it's either 200, 401 or 403. In the first case, nginx proceed with sending the original request to the target backend. In other cases, if you correctly configured nginx, your user should be redirected to Authelia's portal.

Don't hesitate to tell me if something is still unclear and report back any issue with the doc.

**Comment by clems4ever** [comment]
Hello @NegativeFeedback , do you have any news?

**Comment by NegativeFeedback** [comment]
So yes it was upgraded from several versions ago and I attempted to use your suggestions to figure it out but ended up blowing away that machine and rebuilding. I have it working and im sure it was user error as I more or less followed the directions once again for building. 
Thanks for the assistance! It seems like a great piece of software that people should be using more.

**Comment by clems4ever** [comment]
I'm glad it all worked out eventually. Thanks for your the compliment. It's under heavy development and there are a lot more awesome features to come. Stay tuned!

**Comment by Nuanda73** [comment]
Thanks, its worked for me too, we upgraded from an old version (3.9.5) and before the  X-Forwarded-Host not needed (working for us without this) but I added this setting and everything fine now.
