### ISSUE TITLE
index.js missing

### ISSUE THREAD

**Issue by cscottthomas** [clems4ever/authelia#39]
Hi,  I've tried to deploy following the 'Getting started' and it fails.  Authelia container is sat in a state of permanent restart with logs showing:

autheliamaster_auth   "node index.js /etc/a"   34 minutes ago      Restarting (1) 6 minutes ago

Error: Cannot find module '/usr/src/index.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
module.js:472
    throw err;
    ^

when installing with NPM it returns:

npm install -g authelia
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm ERR! Linux 4.4.0-79-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "authelia"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib/node_modules/authelia/src/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/authelia/src/index.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/authelia/src/index.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

Also it wants the src folder to exist within dist/ 

ERROR: Service 'auth' failed to build: lstat dist/src: no such file or directory

I don't think I've done anything incorrectly?  But if so I would appreciate pointing in the correct direction.

Cheers,

**Comment by clems4ever** [comment]
Hello @cscottthomas , thank you for creating this ticket. 
The README was not complete because I forgot to update part of it after the migration into Typescript. Now, before deploying the docker stack, one would need to build the application from Typescript with Grunt and the TS compiler. So, to fix your issue, you probably need to run those two commands before deploying the docker stack:

`npm install --only=dev`
`grunt build`

I made a quick fix in the README but I will enforce the tests of these steps in Travis so that this situation does not happen again.
Tell me if it fixes your issue.

Thanks,
Clément

**Comment by cscottthomas** [comment]
Following these steps and in case anyone else hits the same, I was met with:

:~/authelia-master$ grunt build
/usr/bin/env: ‘node’: No such file or directory

fixed by:
ln -s /usr/bin/nodejs /usr/bin/node

However, this fixed my issue.  Containers up & stable.  Thanks for the help, Clément!

**Comment by clems4ever** [comment]
Hello @cscottthomas , thank you for the feedback. 
I close the issue.
