### ISSUE TITLE
mongodb support in v4?

### ISSUE THREAD

**Issue by hongkongkiwi** [clems4ever/authelia#449]
Hi there,

Is there plans to support mongodb going forward? We use it for all our other services so it would make sense to also store the authelia config inthere, rather than spinning up a mysql db just for authelia.

**Comment by davama** [comment]
👍  +1

**Comment by clems4ever** [comment]
Hello @hongkongkiwi , Authelia will very soon come up with an admin interface and a user interface to manage keys and various security options or be alerted on security issues like credentials compromise or even look at authentication logs. Therefore, it makes more sense to have a relational database in that perspective. Mongo was a good option at the beginning but will likely be limited in the near future that's why I decided to switch.

How hard would it be for you to spin up a db? Are you using Authelia on bare metal? Are you using docker? docker-compose?

**Comment by clems4ever** [comment]
Note that I'm taking the opportunity of the breaking change to do the move and I provide migration scripts to migrate data generated from mongo in v3 into a relational db in v4 (sqlite, mysql or postgres).

**Comment by hongkongkiwi** [comment]
Currently, we have a separate mongodb database server we are maintaining. For development, it's super easy to spin up a mysql instance, but we prefer to keep everything in one DB.

We prefer to use MongoDB as all our other systems are running on it. Perhaps we could have a generic plugin hook architecture? I'm currently playing with MQTT Server VerneMQ which handles this plugin architecture really nicely. It simply has hooks for each call and the plugin just needs a very small amount of code to respond to this hook.

For reference, here's the hooks VerneMQ exposes just to give an idea, it's pretty elegant and simple solution: https://docs.vernemq.com/plugindevelopment/webhookplugins

**Comment by clems4ever** [comment]
Having this kind of architecture for Authelia will be overcomplicated IMHO. It's good for simple message passing protocols but not to replace a complete search query mechanism for rather complex queries (likely joining tables) that will come in the future.

However, I will try to keep the queries as simple as possible for as long as I can and maybe reconsider the question after some time when I have more user feedbacks on v4 and/or if there are many requests in favor of mongo but for the time being I think I will remain with SQL databases for the reasons I mentioned in my previous comments. I'm sorry.
