### ISSUE TITLE
User is sometimes redirected to "already logged in" page after successful authentication

### ISSUE THREAD

**Issue by clems4ever** [clems4ever/authelia#59]
Authelia keeps track of the latest URL where the user comes from so that it can redirect after authentication. In certain scenarii, the redirection URL is an URL to Authelia. So, when the user authenticates he is redirected to the "already logged in" page.

Such a case is for example when the user inputs wrong credentials the first time and good credentials the second time.

**Comment by clems4ever** [comment]
A fix could be to only keeps track of non Authelia urls.

**Comment by clems4ever** [comment]
Not reproducible

**Comment by FrozenDragoon** [comment]
I see you closed this as not reproducible, perhaps I'm doing something wrong. 

In my testing, I have one user and one ACL: allow secret1.test.com (secret2.test.com is my test for deny).
When attempting to access secret2.test.com/secret.html, the redirect to login works, I am prompted to log in.  Upon logging in, I am presented with "You are already logged in".

I believe this to be an issue with the error 401 / HTTP 302 redirect added in 928209dc980dadef16061cde83c3dca9384a7ff0.  

Sample logs:
```
debug: Verify: headers are {"x-original-uri":"/secret.html","x-real-ip":"192.168.2.31","host":"secret2.test.com","connection":"close" [snip]
error: Reply with error 401: FirstFactorValidationError: First factor has not been validated yet.
debug: First factor: headers are {"x-original-uri":"/","host":"authtest.test.com","x-real-ip":"192.168.2.31","connection":"close" [snip]
```
The HTTP302 instructs the browser to make a new connection to the login portal, without carrying over any headers like  ```X-Original-URI $request_uri``` or ```Host $http_host```, so the final redirect does not have anywhere to send the user.  I'm guessing it has to do with [this line](https://github.com/clems4ever/authelia/blob/785182236c9e3f319cf6e8642fbc3aa650826dce/src/server/lib/routes/secondfactor/redirect.ts#L11), it's just always using the second condition (directing the user to ```/```).

I have attempted to append  a ```?redirect=$scheme://$host$request_uri``` to the 302 redirect, but it appears lost in the transition from First Factor to Second Factor.  

Any thoughts/direction?

**Comment by clems4ever** [comment]
Hello @FrozenDragoon, 
Thank you for your feedback. I've just try to reproduce with user **bob** but did not reproduce the issue. I get an error 403 upon successful authentication:
![image](https://user-images.githubusercontent.com/3193257/28983826-c014a77a-795b-11e7-8b16-57e79316a8c5.png)
Can you please help me reproduce with a user of the example environment? 
Are you using version 3.2.0?

**Comment by FrozenDragoon** [comment]
I verified I am using 3.2.0, via the docker image released ~2 days ago. 

I initially had issues with the example environment (didn't realize I needed nodejs-legacy and not just nodejs on Ubuntu), which is why I wasn't testing it, but you're right, it does work perfectly in the provided example.

Something else interesting, in my environment, if I log in and don't get redirected and then log out, then visit the protected page again and log in when prompted, the redirect does work correctly. 

But when starting from scratch, like after clearing the browser cache, it doesn't redirect that first time. Very odd.

Either way, this is clearly user error on my part. Thank you for your reply, and this tool, I'm really liking it  so far.

**Comment by clems4ever** [comment]
Hello @FrozenDragoon ,

I got the issue with the legacy nodejs as well. I should document it somewhere.

For the redirection, if you have a look at the nginx configuration in example/nginx, you'll see those lines:
    
    location /auth_verify {
        internal;
        proxy_set_header  X-Original-URI $request_uri;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  Host $http_host;
    }

They allow Authelia to remember the last URL the user visited which is protected and not coming from auth.test.local. There could be a bug in Authelia but we need to figure out why you are not redirected the first time. We need to know what you did exactly so that I can reproduce it with cucumber tests.

Good you like it! Why are you trying it out? Are you planning to use it in some way? If yes, can you tell me more so that I can have feedback and know how to prioritize improvements?

Don't hesitate to contribute if you wish, by the way.

**Comment by naggie** [comment]
Hi, I was seeing this same issue with my deployment. It turns out that the cause was the change in https://github.com/clems4ever/authelia/blob/master/shared/constants.ts

from 

```
export const REDIRECT_QUERY_PARAM = "redirect";
```
to
```
export const REDIRECT_QUERY_PARAM = "rd";
```
I was aware of this change, but assumed the latest version on NPM reflected the documentation on master which was my mistake.

Please could you publish a new version on NPM.

Thanks for the effort you've put into Authelia, @clems4ever
