### ISSUE TITLE
Configurable LDAP filter

### ISSUE THREAD

**Issue by timaebi** [clems4ever/authelia#70]
The current LDAP configuration allows to set a `base_dn` and an additional DN for each groups and users. It would be very helpful, if one could configure an LDAP filter string like `user_filter` and `group_filter`.

Background:
On my LDAP server the group membership property is `uniqueMember` instead of `member`, which doesn't work with the current implementation. This could be handled with a custom filter with some kind of replacement strings for user DN's.
[Code location](https://github.com/clems4ever/authelia/blob/7be61d73574cc11c0b48a46c2b83665b6a9b2df9/src/server/lib/ldap/Client.ts#L114)

**Comment by clems4ever** [comment]
hello @timaebi, 
you are right, this is clearly a gap for the groups because I indeed hard coded 'member'. However, for the users it should be working already. But anyway a filter would clearly avoid any problem either for users or groups. 
I think I will take the LDAP configuration of Jenkins as an example to implement the feature.

Thank you for the report, it's really helping.

**Comment by clems4ever** [comment]
Hello @timaebi, I'm working on this and it is almost done. It is in a dev branch for the moment but it will be merged soon.

**Comment by clems4ever** [comment]
Hello @timaebi , it is solved with #75. It's in mainstream.

**Comment by timaebi** [comment]
Looks great. Thanks a lot.
I am currently on holiday and will try it out later.

**Comment by clems4ever** [comment]
No problem. Enjoy!
