### ISSUE TITLE
Use email as second factor

### ISSUE THREAD

**Issue by Chemsmith** [clems4ever/authelia#73]
So I was thinking it would be handy if it were possible to use email as an alternate or perhaps backup second factor authentication pathway? Similar to the use of SMS.

Email is probably not as secure as U2F or maybe even a OTP generator but it removes the need for a separate app or device to take advantage of 2FA. Could be optionally enabled.

**Comment by clems4ever** [comment]
Hello @ChemicalNovae,

First, thank you for your interest in Authelia and for this contribution.
Concerning your wish to have email as a second factor, I'm not pretty sure this is a good idea because I've never seen one using it (be it Google, Facebook, Github or whatever) so far. Plus, some people more aware of security concerns than I am do not recommend it as you can read it here for example: https://security.stackexchange.com/questions/94001/email-for-the-second-factor-in-2fa-systems.

So, I don't really want email to be a second factor in Authelia yet, at least as long as I don't have a big community pushing it, but since second factor must be something you "have" or something you "are", perhaps footprint identification could solve your problem (not implemented yet but will be at some point). Or perhaps OAuth could but I'm not familiar enough with it yet to tell.

Hope it helped.

**Comment by ChemicalNovae** [comment]
Hi @clems4ever,

Thanks for the quick reply. That makes sense and I accept the reasoning that email doesn't really add another factor. Partially I wanted it for testing purposes so there wasn't a need to setup multiple token generators for multiple test users. What actually got me thinking about it was that the VPN providor DigitalOcean uses email as a second factor for 2FA and I just happened to be logging in at the time.

Not sure what you mean by "footprint identification", a quick google suggests I should be stalking animals? ;)

Thanks

**Comment by clems4ever** [comment]
Hello, @ChemicalNovae, 
I'm sorry I meant fingerprint... :).
I will definitely have a look at this on DigitalOcean. I have an account but I've never paid attention to this. 
Anyway, I know that testing is a bit complex with only U2F and TOTP but I don't see a simple way to make it easier to test without interfering with production code and don't really want to create weakness points in term of security.
Would it be ok to have a tool that is connected to the DB and get you the TOTP token for any registered user? The use case would be: you have Authelia login page in one window and this tool in another window. You can select the user you want to login with in the tool and it gives you the token in real-time so that you can login easily in the first window. What do you think?

**Comment by ChemicalNovae** [comment]
As handy as that sounds I don't think it's worth expending energy developing. 

But if you think you can do it easily it would definitely make it easier than having to either change the config to enable email (what I ended up doing) or pulling it out of a file each time. I wonder if it becomes a security issue its self though?

**Comment by clems4ever** [comment]
I know what pain it is because I ended up doing this in the integration tests. This what make the run a bit long.
The tool I was talking about would only be a helper and won't be in Authelia's code, so no security issue at all. This would be just a Google Authenticator in-house.

**Comment by clems4ever** [comment]
Concerning your previous edit, I would say the window for attacker is much narrower with the identity validation by email than the email as second factor. With validation, once the link is sent and the secret consumed by the user, nobody will ever access without the secret. The email as second factor gives attackers a small window at each login. You see what I mean?

I don't think I will implement anything for now (neither email as 2FA nor a tool like Google Auth) because I have other tickets I would like to focus on. Can we close the ticket for now? If other people come and push it I would be happy to re-open it.
