### ISSUE TITLE
Flag to return 302 instead of 401 when verifying

### ISSUE THREAD

**Issue by SerialVelocity** [clems4ever/authelia#85]
Hey,

It would be great if there was a flag that we could pass to `/verify` so that it will return 302 instead of 401. Usually, app endpoints would return 302 if not logged in, while API endpoints would return 401. NGINX users usually just change 401 error codes to 302s but other apps (like Traefik) just pass on the error if it is not 2XX.

Cheers,
Ben

**Comment by clems4ever** [comment]
Hello @SerialVelocity , thanks for the feedback. Actually, Authelia is an authentication server that should reply 'yes' or 'no'. Replying with a redirect seems a bit fuzzy to me. Plus, where would Authelia redirect in that case (what if you have several apps in your domain)? 
AFAIC, I think it should only be a matter of config at the level of the reverse proxy.

**Comment by SerialVelocity** [comment]
Several apps in one domain would only affect it if you had Authelia under paths on each subdomain (such as wordpress.example.com/auth/, secret.example.com/auth/, etc). Usually Authelia will know where it lives (like auth.example.com).

The main reason why this might be useful is that you can encode the URL in the query parameters so you always get the right address to redirect to.

The main use-case I've seen in the past is when a web browser opens with all of its old tabs, you don't want all of your old tabs to redirect to just one of the URLs.

Another one is when catching up on your email in the morning, it's common to read the email, click on any links that exist, go to the next email, repeat. Then go to your web browser and see that you haven't logged in so none of the links work.

That could just be solved by adding a redirect URL query parameter to the login page and the reverse proxy can handle the redirect.

**Comment by clems4ever** [comment]
Hello @SerialVelocity , I think there are 2 things in this ticket. I see:
1/ Traefik needs a 302 on /verify to work correctly.
2/ The proxy must redirect the user to correct page after he logged in. (which is already working currently).

So I guess, 1/ could be solved by adding a redirect parameter in the url as you mentionned. If present, Authelia redirects to the provided url or if not present throws a 401 (to still be compatible with nginx which does not seem to forward the redirection like traefik).
And 2/ is already handled AFAIK since when you reach the login page after trying to access a protected resource, the original URI is sent in the header and is stored in the session and used by Authelia to redirect you after completion.

Are we on the same page?
Thank you very much for the details btw.

**Comment by SerialVelocity** [comment]
(1) could be solved by a redirect parameter but I think it might be better to specify it in the configuration as it makes it hard to mess up when setting up multiple subdomains, but up to you, I don't really mind either way as long as it is easy to use.

(2) seems a bit iffy since I constantly open and close my browser, so if I have any Authelia pages open, I'm going to lose any referrer headers that are present (or any session information in general)

**Comment by clems4ever** [comment]
(1) I gave a try with Traefik and I'm a bit sad because the forward auth module could only be applied at the level of the entrypoint. So, you can't choose what you will be securing, it's all or nothing... But anyway, I see the issue with the response. So, I'm going to implement the redirect parameter in the url.

(2) You are right. In that case the referrer will be lost. So what you suggest is not only put the redirect url in the login page url but also pass it across Authelia pages (since authentication is a 2-step process, 2 pages), correct?

**Comment by SerialVelocity** [comment]
(1) #43 solves that issue where you can say these bits are not authed, etc

(2) Yes, exactly.

**Comment by clems4ever** [comment]
Hello, @SerialVelocity 
(1) True, the tests are missing. I will resume when I have some time.
(2) #91 :)

**Comment by clems4ever** [comment]
Hello @SerialVelocity , I'm closing this issue since the remaining work will be treated in #88.
