### ISSUE TITLE
Disable second factor in configuration

### ISSUE THREAD

**Issue by clems4ever** [clems4ever/authelia#87]
Basically, one would like to use Authelia as a basic auth server with a shiny UI :).
Could be done directly in nginx but the UI would be missing.

**Comment by timaebi** [comment]
How about making this configurable per backend application?
I think of a WebDAV calendar server which can not be protected with 2FA because clients don't support 2FA. But it would still be nice to use authelia for the LDAP credentials validation.
On the other hand there are applications that contain more sensible data, where 2FA is required.

We probably also need  step up authentication. What I mean is that if a user first logs into an application without 2FA and then wants to access an other application where 2FA is required. Then he should just be asked for the second factor without username and password.

**Comment by clems4ever** [comment]
Hello @timaebi, you made a point. This is a totally valid case and it is likely to happen. I will raise the priority of this ticket accordingly.

**Comment by clems4ever** [comment]
This is done with #98. It will be documented in README with #99.

**Comment by SerialVelocity** [comment]
Hey @clems4ever, I don't think the right approach is to add it as a query parameter (I may be misreading the code though). Imagine this scenario:
  - You have `supersecret.local` that absolutely needs 2FA
  - You get redirected to `auth.local` to login
  - You append `only_basic_auth=true` to the URL because you only know the users password
  - You can login to the account without 2FA.

That seems bad.

P.S. Doesn't really matter but query parameters are usually `camelCase`

**Comment by clems4ever** [comment]
Hello @SerialVelocity,
The user will be blocked anyway if the app requires 2-factor and even if he provides the flag and set it to true. FYI, the flag is handled by 2 endpoints: "/" and "/verify". The flag provided to "/" is just a helper to redirect the user to the second factor page in one case and to the redirect URL in the other case. If it is provided and set to true for a two factor subdomain, the user is redirected to the app and then redirected again to the login page by nginx since the second factor is still missing...

At the beginning, I saw two ways of solving this problem:
 
1/ The one I implemented that implies there is no config done in Authelia but parameters passed in URL.
2/ There is a config in authelia listing all subdomains where basic auth applies. That way there is no need to provide **with_basic_auth** to the "/verify" endpoint. I could use the "redirect" parameter to detect whether the user needs to be redirected to second factor page or the original app url (because I would know if the subdomain require basic auth). This would be less misleading but I'm not sure adding more config in Authelia is a good idea. And what if the user does not provide the "redirect" parameter? (I would not be able to check where to redirect the user to...) 

Please, tell me what you think would be best?

Ok, for the camelCase format, I will adapt it if I keep the feature as is.

**Comment by jmccoy555** [comment]
Hi @clems4ever 

This is working nicely now in the latest develop but not v3.6.0.

Can I just confirm that by basic_auth you simply mean the user is logging in with a username and password without the 2FA stage, and not that Authelia would support URL encoding e.g https://username:password@my.domain (although according to Wikipedia this has recently been depreciated).

My thinking is, say you have an app that requires you to log in, it would be nice for this to be handled by Authelia making use of all the ACL and other nice features (and a single set up). At the same time it would be nice to use the same domain for a web user to log in by authenticating with Authelia, and thus being logged in if they were to visit any other pages / domains protected by the same credentials (and the shiny log in page!!!). 

At the moment for example I have my.domain pointed at Authelia to handled the basic authentication for a web user, and then also app.my.domain handled by the LDAP plugin in Nginx, for the phone app. It would be nice to remove this second setup. 

I'm not convinced that this is possible. What do you think?

**Comment by SerialVelocity** [comment]
Hey @clems4ever,

Sorry for the late response. I wrote up a large message but I must have forgot to submit it! I think (1) is fine :)

As @jmccoy555 mentions, it should probably be something like `twoFactor=false` since basic auth is something entirely different.

@jmccoy555 That should be possible by proxying everything under `/auth` or `/authelia` to the Authelia server (not sure the path is configurable in Authelia though so it may not work in its current state).

**Comment by clems4ever** [comment]
Please use #81 to resume the discussion on basic auth and tokens.
